easy_infer.py
Someone was supposed to do it but I think it's still going on.
=> Fix: .zip with more than 1 point will have conflicts in the dataset

go-applio-manager.bat
=> Fix installing dependencies

go-applio-manager.sh, go-applio.sh, install_Applio.sh
Los scripts funcionan pero falta que se arreglen problemas basicos de linux relacionados con el propio webui y no el script de instlacion. Se puede hacer un merge perfectamente ahora mismo
=> Linux scripts

assets/configs/config.py
=> If cuda version is unsupported it will use cpu insted

go-applio-manager.sh, go-applio.sh, install_Applio.sh, tabs/resources.py
*Includes intel optimizations (idk if i added it before)
*Make it usable with python3.11++
-Removes mega.py
=> Add python3.11 support on linux

.gitignore, infer-web.py, lib/infer/infer_libs/train/utils.py, lib/infer/modules/train/train.py, tabs/resources.py
- Inference page no longer auto-loads a model to save on VRAM
- Selecting a dataset folder from the dropdown menu sets the "Model Name" to the dataset name
- Added a checkbox for model collapse retraining
- Added a checkbox for overtrain detection
- Changed the default values for:
- Training epochs
- Save latest .ckpt
- Save weights every save point
- Reload on collapse
- Stop on overtraining
- When overtraining detection is enabled, the model will be trained for 100 epochs after the last best epoch was found
- When overtraining detection is enabled, the Tensorboard log interval will be set to every epoch instead of the default 200 steps and only update when a new best has been found
- When overtraining detection is enabled, the "eval" Tensorboard will be updated every epoch, not just the …
=> Overtrain and mode collapse detection

install_Applio.sh
Update install_Applio.sh macOS Features were introduced to modularize…
… the code and make it more readable Homebrew installation is done using a function to keep the script clean.
(New news for macOS)
Features were introduced to modularize the code and make it more readable.
Homebrew installation is done using a function to keep the script clean.
Python 3 installation is handled in a separate function.
The virtual environment creation/activation logic was moved to a function.
The main menu and ending functions were maintained, and the overall flow of the script was improved.
Greater speed to execute
=> Anthonyxd2 mac and linux 

go-applio.sh
Don't let you enter go-applio in previous code
Error fixing previous Souda code
=> Update go-applio.sh Error fixing and added python3 -m venv .venv for better compatibility

Dockerfile, docker-compose.yaml
Nvidia Container Tool kit needed in order to use the GPU (nvidia-container-toolkit). DockerFile improved.
=> Docker compose added. (Now fully Works)

go-applio-manager.sh
Update go-applio-manager.sh New option added to be able to exit and quick access to other Sh files
=> Update go-applio-manager.sh New option added to be able to exit and quick access to other Sh files

go-applio-manager.sh, go-applio.sh, install_Applio.sh
This should fix the issues i opened before and optimize the code a little bit
=> Beter linux and mac scripts

go-applio-manager.sh, go-applio.sh, go-tensorboard.sh, install_Applio.sh
To make scripts faster + more portable towards systems.
=> refactor: get scripts posix-compliant

rvc/train/process_ckpt.py
=> Changed model extraction output path to logs/model_name/model_name.pth

requirements.txt
cuando yo trata de hacer inferencia en mac me daba error de fairseq  Pues lo edite para que sea compatible con mac con ayuda de vidal  pues funciono ya mando foto  de evidencia que funciona correctamente
=> Update requirements.txt fix fairseq mac

run-applio.sh
Antes no podia hacer inferencias  por que no habia compatibilidad con Mps   y que tambien le falta fairseq
ya mando foto de prueba de su funcionalidad
=> Update run-applio.sh Mps inference support

assets/Applio.ipynb
Added Korean Pretrain to custom pretrains on Applio
=> Added KLM Pretrain 32k

.github/workflows/unittest.yml, assets/Applio_NoUI.ipynb, core.py, rvc/train/extract/extract_f0_print.py, rvc/train/preprocess/preprocess.py, rvc/train/train.py, tabs/train/train.py
1. Fixed not showing training process
2. Added cache dataset in gpu option
3. Cpu cores setting in preprocess and extract features
=> Fixes and Updates to Training

requirements.txt
This pull request addresses compatibility issues with dependencies specified in requirements.txt for macOS. The changes were made in response to installation errors encountered on macOS systems, which necessitated adjustments to the versions of certain packages. The updated configuration ensures smooth installation and operation of the required packages on macOS.
**Changes Made:**
- Adjusted version constraints for specific dependencies to resolve compatibility issues on macOS.
- Verified that the updated requirements.txt works without errors on macOS.
=> Fix pip requirements for macOS

rvc/lib/utils.py, rvc/train/extract/extract_f0_print.py
using librosa to load wav files instead of spawning ffmpeg
loading every file into the processing array
using a single model instead of constantly creating new one for every file
=> performance improvement

app.py, core.py, rvc/configs/v1/32000.json, rvc/configs/v1/40000.json, rvc/configs/v1/48000.json, rvc/configs/v2/32000.json, rvc/configs/v2/40000.json, rvc/configs/v2/48000.json, rvc/infer/infer.py, rvc/infer/pipeline.py, rvc/lib/algorithm/generators.py, rvc/lib/algorithm/nsf.py, rvc/lib/tools/prerequisites_download.py, rvc/lib/tools/pretrained_selector.py, rvc/lib/tools/tts.py, rvc/lib/utils.py, rvc/train/data_utils.py, rvc/train/extract/extract_f0_print.py, rvc/train/extract/extract_feature_print.py, rvc/train/extract/preparing_files.py, rvc/train/mel_processing.py, rvc/train/preprocess/preprocess.py, rvc/train/process/extract_index.py, rvc/train/process/extract_model.py, rvc/train/process/extract_small_model.py, rvc/train/process/model_blender.py, rvc/train/train.py, rvc/train/utils.py, tabs/inference/inference.py, tabs/tts/tts.py
https://github.com/blaisewf/rvc-cli
=> Updating the cli

rvc/train/train.py
A small error in where to place the os.environ breaks the multi gpu. Very easy to fix. I tested it on kaggle and at least it worked there
=> Fix Multi-GPU train

rvc/train/process/extract_model.py
A very easy fix that corrects the saving of models generated by overtraining detector
=> Correction for saving the models generated by the overtraining detector

core.py, rvc/train/process/extract_index.py, tabs/train/train.py
This PR adds the option to choose to force Faiss or KMeans to generate the index files. ~~I don't know if the name of the variables is good, so this is something I suggest changing if you have a better name~~
=> Add index algorithm option

assets/presets/Default.json, assets/presets/Good for Anything.json, assets/presets/Music.json, tabs/inference/inference.py
This PR adds presets to the inference tab, thinking more about improving quality of life. The values of the presets will probably be changed in the future to some better ones
=> Add Presets to inference tab

tabs/inference/inference.py
Move presets tab to top of pitch option
Yeah, I should have thought of that
=> Move presets tab up

rvc/train/train.py
This PR tries to make the overtraining detector more accurate
=> Rework of overtraining detector

rvc/lib/tools/launch_tensorboard.py
This PR removes the excessive logs from the tensorboard terminal
=> Remove logs from tensorboard terminal

rvc/lib/utils.py
solved re-download problem for online embedders
=> Update utils.py for re-download problem

rvc/train/extract/pitch_extractor.py
This PR adds multiGPU support to the Pitch Extractor process
=> Support for multiGPU on Pitch Extractor

rvc/train/train.py
This PR adds the discriminator to the overtraining detector, and a file that saves the variables to continue the overtrain detector from where the training left off
=> Add discriminator and continue file for Overtrain Detector

rvc/train/train.py
This PR fixes the overtrain detector not considering increasing values as overtrain
=> Fix overtrain detector at increasing values

run-install.bat, run-install.sh
This PR fixes the omegaconf installation errors if you use the installation script. It's a temporary solution
=> Fix for Omegaconf install in install script

rvc/train/train.py
Fixed the wrong overtrain detector logic I had made
=> Fix overtrain detector mess

rvc/train/train.py
I deleted this by mistake when I was rewriting the Overtrain Detector code...
=> Fix models not being saved

rvc/train/train.py
This PR fixes the model being saved twice if the save every epoch is a multiple of total epoch
=> Fix duplicate saved model

rvc/train/train.py
The code no longer uses a static order of samples when GPU caching setting is if set to false.
=> corrected the the missing shuffle of training samples

core.py
This PR fixes my mistake of not putting the index algorithm argument in train_script
=> Fix core.py train

assets/i18n/languages/en_US.json, core.py, rvc/train/preprocess/preprocess.py, tabs/train/train.py
This PR adds the option to let the user choose whether the audio will be cut by the RVC or not in the preprocess part
This PR closes the issue #578
=> Option to cut or not cut the audios in preprocess

assets/i18n/languages/en_US.json, core.py, rvc/train/preprocess/preprocess.py, tabs/train/train.py
This PR adds the option to disable the preprocess filters
=> Disable filters in preprocess

core.py, rvc/infer/infer.py, rvc/lib/utils.py, tabs/inference/inference.py, tabs/settings/restart.py
This PR changes how batch inference works by not reloading the hubert and voice model
=> Rework batch inference

rvc/train/extract/extract.py
This PR fixes custom embedders
=> Fix embedders

rvc/infer/infer.py, rvc/lib/utils.py
This PR fixes errors when using split audio, and formant shift with folders with a space in the name
=> Fix inference problems

tabs/inference/inference.py, tabs/train/train.py, tabs/tts/tts.py
This PR replaces os.rename with shutil.copy in dropboxes
=> Change os.rename to shutil.copy in dropboxes

rvc/infer/infer.py
This PR fixes hubert not being changed after loading it for an inference
=> Fix the hubert swap

assets/i18n/languages/en_US.json, requirements.txt, rvc/infer/infer.py, rvc/infer/pipeline.py, rvc/lib/tools/prerequisites_download.py, rvc/lib/utils.py, rvc/train/extract/extract.py, tabs/inference/inference.py, tabs/train/train.py
This PR moves Hubert's use of Fairseq to Transformers
Thanks @AznamirWoW for the code!
=> Move from Fairseq Hubert to Transformers Hubert

core.py
This PR fixes the inference by cli not working
=> Fix cli infer

tabs/inference/inference.py, tabs/train/train.py, tabs/tts/tts.py
This PR reactivates the huberts
=> Reenable huberts

rvc/train/train.py
After additional investigation it is apparent that loading a huge data set into the memory cache is not beneficial
=> Reverted the caching functionality to avoid running out of memory

rvc/train/process/extract_model.py, rvc/train/train.py
This PR fixes some mistakes I missed in the previous PR
=> Fix some issues

rvc/train/extract/extract.py, rvc/train/preprocess/preprocess.py
This PR reworks the preprocess and extract feature
Thanks @AznamirWoW for the code!
=> New prepocess and extract

rvc/train/extract/extract.py
This PR fixes the errors when using Crepe in Multi-gpu, as well as making a few changes
=> Fix crepe multi-gpu and changes in Extract

rvc/lib/predictors/F0Extractor.py
=> added fall-back for zluda

core.py, rvc/infer/infer.py, rvc/train/train.py
This PR adds a sample rate check at the start of training and fixes the inference values in cli
=> Fix and sample rate verification

rvc/train/extract/extract.py, rvc/train/process/extract_model.py, rvc/train/process/model_information.py, tabs/extra/model_information.py
This PR adds information about the embedder used in the model
=> Add embedder info

core.py, rvc/train/extract/extract.py, tabs/train/train.py
This PR adds the option to delete the sliced audio folders after finishing the embedder extract
=> Option to delete sliced audio folders

core.py, rvc/train/extract/extract.py, rvc/train/preprocess/preprocess.py, rvc/train/train.py, tabs/train/train.py
This PR removes the option to delete sliced audios. Fixes the preprocess. It also fixes training when no pretrain is selected
=> Remove delete sliced audios and fix preprocess and train

rvc/lib/algorithm/generators.py
=> corrected mismatch between generator and pretrained nonF0 weights

rvc/train/extract/preparing_files.py, rvc/train/train.py
=> corrected flags passed to Synthesizer and extract model functions

tabs/inference/inference.py
This PR fixes a bug that prevented Applio from starting
=> Little fix

assets/i18n/languages/en_US.json, tabs/inference/inference.py
Fixes some things related to the speaker id
=> Fix a few things

rvc/infer/infer.py, rvc/lib/tools/split_audio.py
Also lowered the threshold for silence as with -70dB it did not find any silence gaps.
=> simplified audio split and merge

core.py, tabs/tts/tts.py
This PR adds the option to choose the voice model speaker in the TTS tab
=> TTS speaker

tabs/inference/inference.py, tabs/tts/tts.py
=> Fix speaker ID when it doesn't exist in the file

rvc/infer/pipeline.py
=> Fixed autotune.. does it do anything? Not really.

core.py
This colab fixes colab without UI arguments
=> Fix no UI colab

rvc/infer/infer.py
1) removed unused wavfile import
2) moved audio upscale import so it does not load the model when it is not needed
=> fixed imports for inference module

rvc/train/train.py
=> added audio output for tensorboard

tabs/train/train.py
Leave the option to save only the last G and D files activated
Why this? Because many users don't know about this option and end up running out of space on their SSD/HDs unnecessarily.
=> Leave the option to save only the last G and D files activated

rvc/train/train.py
=> corrected the excessive memory usage

run-install.sh
Installing FFmpeg for Fedora using Flatpack if `dnf` fails
This pull request fixes the problem of this Issue: https://github.com/IAHispano/Applio/issues/781#issuecomment-2394982420
Tested on Nobara Linux (Based on Fedora)
=> Fedora support for install FFmpeg 

requirements.txt
It was giving errors with the previous dependencies
=> Update requirements.txt Update macOS dependence

rvc/train/train.py
=> made a randomly picked, but static reference for tensorboard

core.py
=> Fix infer arguments

rvc/lib/tools/split_audio.py
=> fix for the initial silence being cut out during audio splitting

requirements.txt
Estaba dando errores anteriormente con la version anterior de request el (macOS)
=> Update requirements.txt Fix requests macOS

rvc/train/train.py
This PR fixes an error in training using multiGPU
=> Fix multi GPU train

run-install.sh
macOS's "/usr/bin/apt" is dummy file. So always fail.
cf: https://discussions.apple.com/thread/252845493
I found install error on ffmpeg.
Works on my system.
before:
after:
=> replace brew<->apt check

.github/workflows/pre_compiled.yml, .github/workflows/release.yml
Resolves deprecated node warning from setup-python:
=> Update actions, remove whitespace

tabs/train/train.py
=> limiting the core slider to max cpu cores instead of 64

rvc/infer/infer.py
=> added a check to avoid unnecessary VC reload

rvc/infer/pipeline.py
=> Another performance improvement ~0.3sec/call

rvc/train/extract/extract.py
=> fixed embedder value save

core.py
=> fixed extra parameters added due to a bad merge

tabs/inference/inference.py
fixed the speaker_id bug i mentioned in issues
all details are here https://github.com/IAHispano/Applio/issues/847
tested only that part
just added sid_batch to refresh button
=> fix the speaker_id bug i mentioned in issues

rvc/train/train.py
- removed optimizer steps left from an attempt to fix grading buckets
- corrected the error message for incompatible model
- simplified the train unpacking
- fixed an incorrect move of cached tensors to a wrong device
- grouped gradients under the same section for tensorboard output
=> minor bugfixes and code cleanup

rvc/train/mel_processing.py, rvc/train/train.py
replaced mel spec L1 loss with more comprehensive calculation for better training results
minor fixes:
moved image generation to the end of the loop
audio preview is no longer saved every epoch, changed it to do that every time the model is saved
=> replaced mel loss function with a better alterntive, general fixes for train loop

assets/i18n/languages/sr_RS.json
Updated Serbian language
Added new required strings
It's tested by installing Applio using Windows and Debian
=> Serbian Language Updated

.github/workflows/code_formatter.yml, assets/themes/Applio.py, rvc/train/extract/extract.py, rvc/train/train.py, tabs/voice_blender/voice_blender.py
I am not very familiar with GitHub and couldn't figure out the previous PR, so I am opening a new one.
=> Adding autoflake to workflows

run-install.sh
I have noticed that some developers use custom Python paths, perhaps through Python 3 or Python 3.10. x using Python
My environment at that time was Python 3.10.11, but it still displayed my local Python 3.13
=> Add more detailed Python version check
