IAHispano/Applio

lib/infer/modules/uvr5/mdxprocess.py

Simple fix for applio attempting to create directories at / which doesn't work (and then exits) unless it's executed with privileges.
Not too sure why the commit changes the last line of the file though, github web editor seems to do that :man_shrugging:

fix mdxprocess.py

---

assets/requirements/requirements.txt
infer-web.py
lib/tools/model_fetcher.py

- Bumps pyworld to 0.3.4 to avoid compilation issues on most linux systems (0.3.3 requires manual steps to get working, 0.3.4 works as is)
- Remove some questionable code that filters out the supported GPU display on the training page. If a GPU is deemed as unsupported, it just didn't list it, even though that GPU could very well be used (e.g. AMD cards on the ROCm pytorch build)
- Replaces a questionable `rmdir` call that attempted to remove /s and /q on linux, since rmdir doesn't treat those as flags. 
For the GPU training display, one downside is that we're now also displaying cards that aren't quite supported (e.g. GTX 9xx cards and older). Not sure on how to deal with it properly, I don't think the torch API allows to test a device cleanly.
Unrelated, but is the makefile still …

Some linux fixes

---

go-tensorboard.sh

First. the installer is going to creacte a virtual env for python. like in conda.
This will pass PEP 668 in later versions of linux (3.9+) or common known has pip don't installing dependencies.
Is like the node_modules but for python
The venv create .venv where the python version where we get
`activate  activate.csh  activate.fish  Activate.ps1  pip  pip3  pip3.11  python  python3  python3.11`
Activate is to activate the venv. and has you can see python always is going to have 3 names here  python  python3  python3.11.
If we only use python(version here) this will break the compat for other python versions.
The code should always refer to python as `python` or `python3`.
This may ocassion a question
¿Then why is $py used in the installer?. In some distros or systems python for some reason …

Fix go-tensorboard.sh calling python3.9 insted of just python

---

go-applio-manager.bat

An error was being thrown on the windows launch due to PyTorch not being the version required.  It required 2.1.

Update go-applio-manager.bat for PyTorch 2.1

---

.github/workflows/unittest.yml
rvc/train/extract/extract_feature_print.py
rvc/train/slicer.py
rvc/train/train.py
tabs/inference/inference.py
tabs/train/train.py

See the commits below for details.
(If only some folks stop using the word "bloat" when it's the complete opposite: more of like some mistakes were made when cleaning up the code.)

Various fixes.

---

rvc/train/preprocess/preprocess.py

Speed up preprocessing, as there are no real reasons on why would someone disable multiprocessing (unless the system is too weak to handle it, but that's an esoteric case).

preprocess.py: always parallel

---

tabs/download/download.py

os.rename does not work if the folders are mounted on different filesystems. Some operating systems mount /tmp on a different filesystem (such as with mine), due to which /tmp/gradio is not able to symlink to the model in log. This solves that issue

Changed os.rename to shutil.move

---

app.py

Added fallback logic that selects a different port if gradio returns an `OSError`.
If the error is triggered, gradio will be launched again on a port decreased with -1.
There is a limit of max 10 attempts to prevent a infinite loop.
Why I added this:
I ran into the problem that port 6969 is already in use.
I have always fixed this issue by changing the port in the app.py to something else, but with every git pull I had to change it again and was craving for a long term solution.
Why you should consider merging:
the same problem for any other user without the technical knowledge to resolve it themselves runs into the same problem can be avoided.

Add fallback logic to select different server port on OSError.

---

core.py

currently the core.py file runs the inference scripts using the hardcoded `python` command.
this is problematic when running inside a venv because the `subprocess.run()` starts a new process without inheriting the python executable that was used to run the parent process, and results in dependency errors (since it tries to look for dependencies in the globally installed python environment instead of the current venv when running inside a venv).
by using `sys.executable`, we can solve this. it will automatically use the globally installed python when running normally, and it will use the python in the current venv when running in a venv.

automatically use the correct python executable

---

rvc/configs/config.py
tabs/train/train.py

As the name of the PR suggests, it automatically sets the maximum number of GPUs available in the system for Extract Feature and training. This is also a temporary fix for a bug where Applio fails to start the pitch extract process when there are multiple GPUs, but only one is selected, which ends up using CPU in the process.

Auto set maximum number of available gpus

---

rvc/train/train.py
rvc/train/utils.py

corrected the training to resume so it does not overwrite the latest saved epoch
results: 
1) if the last epoch was 100, restart begins at 101
2) tensorboard shows correct output as  tfevents log contains reasonable results
loss/g/total,29.556018829345703,31104.0
loss/g/total,31.021081924438477,31320.0
loss/g/total,31.071796417236328,31536.0
loss/g/total,30.628948211669922,31752.0
loss/g/total,15.241731643676758,31968.0
loss/g/total,29.393726348876953,32184.0
loss/g/total,32.008575439453125,32400.0
loss/g/total,29.7031192779541,32616.0
loss/g/total,28.384408950805664,32832.0
after resume
loss/g/total,32.188724517822266,33000.0
loss/g/total,28.97464370727539,33110.0
loss/g/total,25.699451446533203,33220.0
loss/g/total,29.753664016723633,33330.0
loss/g/total,28.753559112548828,33440.0 …

Corrected resume functionary for training

---

assets/i18n/languages/en_US.json
rvc/train/train.py
tabs/settings/restart.py
tabs/train/train.py

The stop training button isn't working because it's saving the pid_file in a different directory than the one the stop function expects
Edit: I changed the train button to work in a different way
Edit2: This PR also fixes the following warning
```
/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:136: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
```

Change in the stop training button and fix step warning

---

rvc/train/preprocess/preprocess.py

Small fix that fixes the preprecess if the number of cores is not specified when calling core.py

Fix preprocess if the number of cores is not specified

---

assets/i18n/languages/en_US.json
core.py
rvc/train/process/extract_model.py
rvc/train/process/model_information.py
rvc/train/train.py
tabs/extra/extra.py
tabs/extra/model_information.py
tabs/extra/processing/processing.py
tabs/train/train.py

This PR adds more information about the model to .pth

Add more information to the model

---

rvc/train/preprocess/preprocess.py

In the previous code, preprocess was taking too long because it had to read all the files twice
Doing the preprocess part

Fix preprocess taking too long

---

requirements.txt

This PR updates gradio version which fixes Pydantic-core 2.23.2 bug, that breaks Gradio UI.
Without this fix WebUi would not work.
Info about bug: [https://github.com/gradio-app/gradio/issues/9278](https://github.com/gradio-app/gradio/issues/9278)
This fixes #670. 
Was tested on Linux - Ubuntu 22.04.
- [x ] My code follows the code style of this project.
- [ x] All new and existing tests passed.

Updated gradio version for Pydantic-core bug fix

---

rvc/lib/predictors/FCPE.py

Added missing fall-back for Zluda for FCPE predictor torch.stft call

added missing fallback for stft

---

tabs/tts/tts.py

Open text file with utf-8 encoding
Added utf-8 encoding when opening a text file upladed in tts tab to prevent unicode errors
Text upload fails if the text file contains non-unicode letters. Explicit utf-8 encoding when opening the file fixes this issue.
Uploading a file with non-unicode letters resulted in a UnicodeDecodeError

Prevents Unicode decode errors in TTS text file upload

---

run-install.sh

- Fix to Error: Command '['/home/MyPC/Applio-3.2.5/.venv/bin/python3.10', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
./run-install.sh: 36: .: cannot open .venv/bin/activate: No such file
- Tested locally in Ubuntu 24.04.1
- ensurepip was changed to get-pip.py in case of error
- Now FFmpeg will be installed using sudo

Fix Install pip error in Linux (Debian/Ubuntu) 

---

run-install.sh

Obtimizations for `run-install.sh` and install ffmpeg funcion
Shebang Change: This now reflects `#!/bin/bash` for better compatibility with different systems. Error Handling: Added `set -e` to the beginning to make sure the script exits if any of the commands fail. Logging Function: I have implemented `log_message()` to log messages including their timestamps. Python Version Detection: I used the function `find_python()` which searches in order for `python3.10`, then `python3`, and finally `python`.
• **FFmpeg Installation:** Improved install_ffmpeg() with command -v instead of which; improved Flatpak fallback mechanism.
• **Flatpak Installation:** Improved install_ffmpeg_flatpak() to be able to install Flatpak if not present. Handling more package managers.
• **Virtual Environment …

Obtimizations and improvedments for run-install.sh

---

run-install.sh

habia un usuario que tenia un error de instalacion de  ffmpeg  pues lo modifique para que cuando se instale no te hagas que usar export o otros tipos de comando una instalacion mucho mas facil para el usuario de macOS
(foto de de evidencia)

Update run-install.sh Fix brew ffmpeg   and export macOS

---

rvc/train/preprocess/preprocess.py

In order to avoid an unexpected volume boost of the quiet split parts

moved audio normalization to pre-splitting

---

rvc/infer/pipeline.py

numpy.int was [deprecated in NumPy 1.20](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations) and was [removed in NumPy 1.24](https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations).
https://stackoverflow.com/questions/74946845/attributeerror-module-numpy-has-no-attribute-int
Motivation is to run Applio on numpy 1.24+ environments and silence the warning on numpy 1.20 to 1.23
Tested on numpy 1.24 and 1.23

fix: AttributeError: module 'numpy' has no attribute 'int'

---

run-install.sh

1- Python 3.9 support: Added to the list of versions searched for in the find_python function.
2- Python installation on macOS: Python 3.9 is included as an option to install using Homebrew if it is not present.
3 - brew faiss

macOS install fix

---

rvc/train/process/extract_model.py
rvc/train/train.py
rvc/train/utils.py

Current implementation saves two copies of model, reloads from disc, modifies, then replaces the original one. This produces excessive IO during the saving (both due to reloading the model from disc, and storing it twice) which is critical for short save intervals, especially during fine-tuning.
Additionally, this fixes the model not being overwritten when re-running the training. This makes more sense due to at least two reasons:
1. Retraining the same data set with different precision produces models with the same name. So if you trained the model with a different precision before and switch, then you train generator and discriminator, but never produce a final model until new epoch.
2. Retraining in general always produces a different model, so you cannot consider an already existing …

Remove double torch.save

---

rvc/train/train.py

This changes the backend from GLOO to NCCL for macOS and Linux targets using CUDA and keeping GLOO for Windows using any GPU since NCCL is not compiled for it. This also conditionally disables the use of libuv for Windows since pytorch >2.4 is compiled without libuv.
https://pytorch.org/tutorials/intermediate/TCPStore_libuv_backend.html#impact
This does not break compatibility with ROCm since ROCm pytorch uses RCCL under the hood:
https://discuss.pytorch.org/t/ddp-with-amd-rocm/118928/2
This allows for the usage of latest PyTorch versions and keeping distributed training on Windows while using NCCL on other OS to improve multi-gpu CUDA performance on Linux runners.
Run the code with Nvidia GPU on Windows and Linux. The code runs with PyTorch >2.4 on Windows, previously failed to run due …

Use NCCL and toggle libuv for compatibility with latest pytorch versions

---

app.py

1. Remove func `get_port_from_args()`
2. Add func `get_value_from_args()` to enhance code reusability.
3. Add some type annotations to params and returns
4. Add param `--server-name <ip>` for gradio
Some time we need to run it with ip `0.0.0.0` but now it couldn't do that.
I run that on my local server bcz I think it is a tiny change for the code.
None.

Add a param `--server-name` to support providing server_name for gradio

---

rvc/lib/utils.py

Modified the `format_title` function to preserve non-ASCII characters (such as Chinese characters) while maintaining the existing functionality for special character handling and space replacement. Removed the ASCII encoding/decoding step and added Unicode support to regex patterns.
The previous implementation was converting all non-ASCII characters to underscores, which resulted in loss of information for titles containing Chinese or other non-ASCII characters. This fix ensures that these characters are preserved while still cleaning up unwanted special characters.
Tested with various input strings including:
Chinese characters: "歌曲名字-艺术家.wav" → "歌曲名字-艺术家.wav"
Mixed language: "歌曲名字-艺术家 v2.0.wav" → "歌曲名字-艺术家_v2.0.wav"
Special characters with Unicode: "歌曲名字├──艺术家.wav" → "歌曲名字艺术家.wav" …

Preserve non-ASCII characters in title formatting

---

run-install.sh

Not everyone has HomeBrew installed in /opt/homebrew. This uses the `brew --prefix`, which is the official way to get the prefix.
Instead of the hard path of "/opt/homebrew", the script will fetch the path from HomeBrew itself.
This change is for people who install HomeBrew to a different prefix than "/opt/homebrew". Some people need custom locations for disk space, clashing dependences for other programs, or any other reasons.
Ran install script, and it works. 
Tested on my Mac Studio Apple M1 Ultra 64 GB, 48 GPU cores

Allow HomeBrew installed in a different prefix

---

rvc/configs/config.py

The config file for 44100 had been removed but rvc/configs/config.py was still trying to load it, causing this error:
```
Traceback (most recent call last):
File "/home/joseph/Documents/Source/Managed/Applio/app.py", line 26, in <module>
from tabs.extra.extra import extra_tab
File "/home/joseph/Documents/Source/Managed/Applio/tabs/extra/extra.py", line 10, in <module>
from tabs.extra.sections.f0_extractor import f0_extractor_tab
File "/home/joseph/Documents/Source/Managed/Applio/tabs/extra/sections/f0_extractor.py", line 6, in <module>
from rvc.lib.predictors.F0Extractor import F0Extractor
File "/home/joseph/Documents/Source/Managed/Applio/rvc/lib/predictors/F0Extractor.py", line 15, in <module>
config = Config()
File "/home/joseph/Documents/Source/Managed/Applio/rvc/configs/config.py", …
```

remove 44100 config file from list of config files.

---

rvc/lib/predictors/F0Extractor.py

This PR fixes a method signature mismatch in the F0 extraction pipeline that caused a `TypeError` during conversion. The error:
```
Traceback (most recent call last):
...
File "/tmp/Applio/rvc/lib/predictors/F0Extractor.py", line 88, in extract_f0
return self.hz_to_cents(f0, librosa.midi_to_hz(0))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: F0Extractor.hz_to_cents() takes from 1 to 2 positional arguments but 3 were given
```
I turned the method to `@staticmethod` because the method is a pure mathematical operation that requires no access to instance-specific data (`self`). While we could add `self` as the first parameter to resolve the error, using `@staticmethod` better reflects the method's stateless nature and avoids misleading future developers into thinking it interacts …

Fix parameter mismatch in F0 cents conversion

---

assets/Applio_Kaggle.ipynb

Disabling FireBrowser Authentication will make the user with id1 the default one, but creating it with a blank password, will mess up the login, making so you can't login in FileBrowser.
It solves an issue that wouldn't let users see the files.
It has been tested on a normal Kaggle Environment.

Fix FileBrowser Login

---

rvc/train/mel_processing.py

- Replace spectral_normalize_torch/dynamic_range_* with inline torch.log in spec_to_mel_torch
- Remove unused helper functions
I don't quite understand why separate functions are needed for this. I propose to simplify the code by removing these unnecessary and unused, in my opinion, functions 🤷🏻‍♂️

Refactor: inline mel log compression; remove unused dynamic range compression (DRC) helpers
